### ISSUE TITLE
Killed worker when using dask-geopandas with distributed client

### ISSUE THREAD

**Issue by jorisvandenbossche** [jsignell/dask-geopandas#5]
Just locally on my laptop, but I can't get a distributed client to work, while the default dask threaded scheduler works, ánd a plain dask.dataframe also works with distributed.

What I am doing to test is:

```python
import geopandas
import dask.dataframe as dd
import dask_geopandas

from distributed import Client
client = Client()
client

# loading a geopandas GeoDataFrame
df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))

# first creating a pure dask DataFrame (getting non-geometry columns)
ddf = dd.from_pandas(df[['pop_est', 'continent', 'name']], npartitions=4)

# this works fine
ddf.continent.value_counts().compute()

# now creating a dask_geopandas.GeoDataFrame
ddf = dask_geopandas.from_geopandas(df, npartitions=4)

# the same thing now fails (only getting the column as a dask.Series from the GeoDataFrame)
ddf.continent.value_counts().compute()
```

and this fails with:

```
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-32-f1c611ca664d> in <module>
----> 1 ddf.continent.value_counts().compute()

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2593                     should_rejoin = False
   2594             try:
-> 2595                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2596             finally:
   2597                 for f in futures.values():

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1885             else:
   1886                 local_worker = None
-> 1887             return self.sync(
   1888                 self._gather,
   1889                 futures,

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    777             return future
    778         else:
--> 779             return sync(
    780                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    781             )

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1750                             exc = CancelledError(key)
   1751                         else:
-> 1752                             raise exception.with_traceback(traceback)
   1753                         raise exc
   1754                     if errors == "skip":

KilledWorker: ("('from_pandas-35d27145a3c0b4d3be6e6daa6537420f', 0)", <Worker 'tcp://127.0.0.1:46111', name: 2, memory: 0, processing: 4>)
```

Any ideas on where to look to debug this?

**Comment by jorisvandenbossche** [comment]
OK, reading https://stackoverflow.com/questions/46691675/what-do-killedworker-exceptions-mean-in-dask mentioned to look at the worker logs in stdout, which reminded me that when working in a notebook, you don't see those directly but only in the terminal where you started the notebook. And indeed, that gives a more understandable error:

```
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/home/joris/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/protocol/core.py", line 124, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/home/joris/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 268, in deserialize
    return loads(header, frames)
  File "/home/joris/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 62, in pickle_loads
    return pickle.loads(b"".join(frames))
  File "/home/joris/miniconda3/envs/geo-dev/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "/home/joris/scipy/repos/pyproj/pyproj/crs/crs.py", line 295, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2332, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)
distributed.core - ERROR - Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)
```

so something is wrong with my pyproj installation.

**Comment by jorisvandenbossche** [comment]
Turns out the processes were not picking up the correct proj version, something to do with my local installation, so closing.
